### ISSUE TITLE
Cam Jam EduKit 2 worksheet Two LEDs and buzzer

### ISSUE THREAD

**Issue by Joumasesoep** [CamJam-EduKit/EduKit2#2]
![camjam](https://user-images.githubusercontent.com/30775824/29004778-063d71d4-7abd-11e7-95e7-4dc15ecb7c44.jpg)

Hi
I am continuously getting a syntax error. See attached Scrot.
Excuse me this is the first time playing around with this so excuse the ignorance.

Regards

**Comment by Pyroseza** [comment]
Random question, are you South African?

**Comment by Joumasesoep** [comment]
Yes i am. Why?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Pyroseza <notifications@github.com> Date: 2017/08/07  01:25  (GMT+02:00) To: CamJam-EduKit/EduKit2 <EduKit2@noreply.github.com> Cc: Joumasesoep <carl.douglas.larsen@gmail.com>, Author <author@noreply.github.com> Subject: Re: [CamJam-EduKit/EduKit2] Cam Jam EduKit 2 worksheet Two LEDs and buzzer (#2) 
Random question, are you South African?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CamJam-EduKit/EduKit2","title":"CamJam-EduKit/EduKit2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CamJam-EduKit/EduKit2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Pyroseza in #2: Random question, are you South African?"}],"action":{"name":"View Issue","url":"https://github.com/CamJam-EduKit/EduKit2/issues/2#issuecomment-320539648"}}}

**Comment by Pyroseza** [comment]
Me too. I had a good laugh at your username :)

**Comment by Pyroseza** [comment]
Back to the issue, arr you having a problem calling the RPi library?

**Comment by Joumasesoep** [comment]
Lol great to hear.where are you based


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Pyroseza <notifications@github.com> Date: 2017/08/07  09:03  (GMT+02:00) To: CamJam-EduKit/EduKit2 <EduKit2@noreply.github.com> Cc: Joumasesoep <carl.douglas.larsen@gmail.com>, Author <author@noreply.github.com> Subject: Re: [CamJam-EduKit/EduKit2] Cam Jam EduKit 2 worksheet Two LEDs and buzzer (#2) 
Me too. I had a good laugh at your username :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CamJam-EduKit/EduKit2","title":"CamJam-EduKit/EduKit2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CamJam-EduKit/EduKit2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Pyroseza in #2: Me too. I had a good laugh at your username :)"}],"action":{"name":"View Issue","url":"https://github.com/CamJam-EduKit/EduKit2/issues/2#issuecomment-320585408"}}}

**Comment by Joumasesoep** [comment]
Are you able to vnc to have a look?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Pyroseza <notifications@github.com> Date: 2017/08/07  09:05  (GMT+02:00) To: CamJam-EduKit/EduKit2 <EduKit2@noreply.github.com> Cc: Joumasesoep <carl.douglas.larsen@gmail.com>, Author <author@noreply.github.com> Subject: Re: [CamJam-EduKit/EduKit2] Cam Jam EduKit 2 worksheet Two LEDs and buzzer (#2) 
Back to the issue, arr you having a problem calling the RPi library?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CamJam-EduKit/EduKit2","title":"CamJam-EduKit/EduKit2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CamJam-EduKit/EduKit2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Pyroseza in #2: Back to the issue, arr you having a problem calling the RPi library?"}],"action":{"name":"View Issue","url":"https://github.com/CamJam-EduKit/EduKit2/issues/2#issuecomment-320585693"}}}

**Comment by Pyroseza** [comment]
I'm actually based in the UK, moved here just over a year ago.

Yeah I could do, send the connection details directly to my email:
jarpri08@gmail.com

**Comment by Pyroseza** [comment]
@Joumasesoep did you come right?

**Comment by Joumasesoep** [comment]
Hi Pyroseza
Yes i am still battling with this.
Are you working today?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Pyroseza <notifications@github.com> Date: 2017/08/10  16:52  (GMT+02:00) To: CamJam-EduKit/EduKit2 <EduKit2@noreply.github.com> Cc: Joumasesoep <carl.douglas.larsen@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [CamJam-EduKit/EduKit2] Cam Jam EduKit 2 worksheet Two LEDs and buzzer (#2) 
@Joumasesoep did you come right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CamJam-EduKit/EduKit2","title":"CamJam-EduKit/EduKit2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CamJam-EduKit/EduKit2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Pyroseza in #2: @Joumasesoep did you come right?"}],"action":{"name":"View Issue","url":"https://github.com/CamJam-EduKit/EduKit2/issues/2#issuecomment-321575137"}}}

**Comment by Pyroseza** [comment]
Yeah I can still take a look but it's got to be now as later I'll be playing cricket and that will last several hours.

**Comment by Joumasesoep** [comment]
Thanks for the response. I sorted it out now. The manual said to type the code in word for word but the i should be lowercase and not caps.
Wanted to tell you we in process of selling up and immagrating to IK as well. Will chat next week about it with you 
Good luck with the cricket and thanks for the help again


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Pyroseza <notifications@github.com> Date: 2017/08/12  10:16  (GMT+02:00) To: CamJam-EduKit/EduKit2 <EduKit2@noreply.github.com> Cc: Joumasesoep <carl.douglas.larsen@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [CamJam-EduKit/EduKit2] Cam Jam EduKit 2 worksheet Two LEDs and buzzer (#2) 
Yeah I can still take a look but it's got to be now as later I'll be playing cricket and that will last several hours.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CamJam-EduKit/EduKit2","title":"CamJam-EduKit/EduKit2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CamJam-EduKit/EduKit2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Pyroseza in #2: Yeah I can still take a look but it's got to be now as later I'll be playing cricket and that will last several hours."}],"action":{"name":"View Issue","url":"https://github.com/CamJam-EduKit/EduKit2/issues/2#issuecomment-321965748"}}}

**Comment by Pyroseza** [comment]
Oh lol! The Import -> import
Nice one, good luck with that!

**Comment by Pyroseza** [comment]
@joumasesoep, can you please close the issue when you get a chance?

**Comment by GeekyTim** [comment]
Glad you two could help each other :-)
