### ISSUE TITLE
Missing some information

### ISSUE THREAD

**Issue by Georgielaa** [CamJam-EduKit/EduKit2#4]
CamJam EduKit 2 - Sensors Worksheet 3 (GPIO Zero) - Temperature.pdf

In the project description you reference that we will have to use the rpi.gpio library for this because gpiozero has no support for the one wire interface, with no more reference to it in the project.
When you try to run the code you end up with this error:-

Traceback (most recent call last):
  File "/home/pi/python_scripts/CamJam Edukit 2/3-temperature.py", line 6, in <module>
    from w1thermsensor import W1ThermSensor
ImportError: No module named 'w1thermsensor'

I noticed that the rpi.gpio worksheet 3 has four pages instead of the three this version has, so maybe missed a page!?

**Comment by GeekyTim** [comment]
The instructions for installing the additional library are in Worksheet 1.  I will be updating the worksheets to make it clearer.
